version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    allow:
      - dependency-name: "jina"
#     ignore:
#       # ignore jina patch updates
#       - dependency-name: "jina"
#         update-types: ["version-update:semver-patch"]
