name: Version Update

on:
  pull_request:
    paths:
      - requirements.txt

jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      
      - name: Install Dependencies
        run: |
          go mod tidy
          pip install -r requirements.txt
          sudo apt-get update
          wget https://github.com/protocolbuffers/protobuf/releases/download/v21.7/protoc-21.7-linux-x86_64.zip
          unzip protoc-21.7-linux-x86_64.zip -d $HOME/.local
          # https://stackoverflow.com/a/62872353/15683245
          go get -u google.golang.org/protobuf/cmd/protoc-gen-go
          go install google.golang.org/protobuf/cmd/protoc-gen-go
          go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
      
      - name: Get Jina & Docarray Versions
        id: versions
        run: |
          echo "::set-output name=JINA_VERSION::$(jina -v)"
          echo "::set-output name=DOCARRAY_VERSION::$(python -c "import docarray; print(docarray.__version__)")"

      - name: Download proto files 
        run: |
          bash scripts/fetchProtos.sh ${{ steps.versions.outputs.JINA_VERSION }} ${{ steps.versions.outputs.DOCARRAY_VERSION }}

      - name: Generate Golang Code from protos
        run: |
          export GOROOT=/usr/local/go
          export GOPATH=$HOME/go
          export GOBIN=$GOPATH/bin
          export PATH="$PATH:$GOROOT:$GOPATH:$GOBIN:$HOME/.local/bin"
          bash scripts/protogen.sh

      - name: Setup tmate session for debugging
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
