name: Client Tests

on:
  pull_request:

jobs:
  core-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Golang 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Dependencies
        run: |
          go mod tidy -v
          go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.1.6 
          go get github.com/onsi/ginkgo/v2/ginkgo/internal@v2.1.6
          go get github.com/onsi/ginkgo/v2/ginkgo/labels@v2.1.6
          go install github.com/onsi/ginkgo/v2/ginkgo
          go get github.com/onsi/gomega/...
          go mod tidy -v

      - name: Run Client Tests
        run: ginkgo --succinct --progress
        env:
          ACK_GINKGO_RC: true
          ACK_GINKGO_DEPRECATIONS: 1.16.5

  success-all-test:
    needs: core-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "All Done"
