name: Tag & Release

on:
  push:
    branches:
      - main
    paths:
      - requirements.txt

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Get Jina & Docarray Versions
        id: versions
        run: |
          echo "::set-output name=JINA_VERSION::$(jina -v)"
          echo "::set-output name=DOCARRAY_VERSION::$(python -c "import docarray; print(docarray.__version__)")"

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.versions.outputs.JINA_VERSION }}
          name: Release ${{ steps.versions.outputs.JINA_VERSION }}
          body: Automated release for jina ${{ steps.versions.outputs.JINA_VERSION }} with docarray ${{ steps.versions.outputs.DOCARRAY_VERSION }}
